name = "TigerLine"
uuid = "9a9a8258-a423-4c9c-ac3d-7cc63de3c137"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>", "Jacob Zelko <jacobszelko@gmail.com>", "and contributors"]
version = "0.1.0-DEV"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
TidierVest = "969b988e-7aed-4820-b60d-bdec252047c4"

[compat]
Aqua = "0.8"
Format = "1.3"
TidierVest = "0.4.3"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
